### ISSUE TITLE
能否提供 WebGL 支持

### ISSUE THREAD

**Issue by zhiqingchen** [flyskywhy/react-native-gcanvas#1]
> `@flyskywhy/react-native-gcanvas` only support render2d canvas as described in `Java_com_taobao_gcanvas_GCanvasJNI_render()` of `core/android/GCanvasJNI.cpp`.

为何只能支持 2d

**Comment by flyskywhy** [comment]
因为之前阿里的文档中说 WebGL 的相关函数 extendCallNative 是仅支持 iOS 的，为了让 Android 和 iOS 保持一致，我先只支持 2d 。
后续有时间我再测测是否能在 Android 上也支持 WebGL ，因为阿里的文档也可能已过期 :P

**Comment by flyskywhy** [comment]
@zhiqingchen ，请提供一些类似目前 [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) 中 drawSome() 内容的 WebGL 相关的测试代码，以便我调试，谢谢！

**Comment by zhiqingchen** [comment]
https://github.com/alibaba/GCanvas/issues/47

还没搞到webgl，目前卡到上面的问题了😅

**Comment by flyskywhy** [comment]
@flyskywhy/react-native-gcanvas@2.1.0 support 3D WebGL :laughing:
