### ISSUE TITLE
why "0" shown?

### ISSUE THREAD

**Issue by WhyCloudy** [flyskywhy/react-native-gcanvas#13]
When I take any action with context, a "0" will show on the left top of canvas
Even a 
`ctx.font = '24px Arial'`
then the 0 shown.
Draw a picture(just like demo code), and after random time, a '1' will show to cover 0
Could some one help, thx

无论对context做任何操作，比如 ctx.font = 什么，或者ctx.fillText，左上角都会出现一个 0 (位置就是最左上角)，如果设置了字体，那么0也会是对应的字体
在我渲染了个图片或者其他的什么，过会又会出现一个“1” 覆盖在0上面
想咨询下这是什么东西呀

**Comment by flyskywhy** [comment]
你是不是将 `node_modules\@flyskywhy\react-native-gcanvas\components\GCanvasComponent.js` 中的
```
// ReactNativeBridge.GCanvasModule.setLogLevel(0);
```
修改成
```
ReactNativeBridge.GCanvasModule.setLogLevel(0);
```
了？

**Comment by WhyCloudy** [comment]
> 你是不是将 `node_modules\@flyskywhy\react-native-gcanvas\components\GCanvasComponent.js` 中的
> 
> ```
> // ReactNativeBridge.GCanvasModule.setLogLevel(0);
> ```
> 
> 修改成
> 
> ```
> ReactNativeBridge.GCanvasModule.setLogLevel(0);
> ```
> 
> 了？

没有呢，我yarn add --force了，确保没有对node_modules下属的文件进行修改
结果还是有0

我又尝试着真的去修改下这个文件，把setLoglevel改成4
但是还是有0出现。。。

**Comment by WhyCloudy** [comment]
只测试了ios模拟器和真机，安卓的还没测

**Comment by WhyCloudy** [comment]
`import * as React from "react";
import {Platform} from "react-native";
import {useState} from "react";
// @ts-ignore
import {GCanvasView, GImage} from '@flyskywhy/react-native-gcanvas';
import {Button} from "react-native";

export const TestScreen = () => {
  const [testCanvas, setTestCanvas] = useState()
  const [ctx, setCtx] = useState<CanvasRenderingContext2D>()

  return <>
    {Platform.OS === 'web' ? (
      <canvas
        style={
          {
            width: 200,
            height: 300,
          } /* canvas with react-native-web can't use width and height in styles.gcanvas */
        }
      />
    ) : (
      <GCanvasView
        onCanvasCreate={(canvas: any) => {
          setTestCanvas(canvas);
          setCtx(canvas.getContext('2d'))
          canvas.getContext('2d').font = '24px Arial';

        }}
        style={{width: '100%', height: '80%'}}
      />
    )}
    <Button title={"画"} onPress={() => {
      if (!ctx) {
        return
      }
      ctx.fillText("test", 300, 400)

      ctx.beginPath();

      //circle
      ctx.fillStyle = 'blue';
      ctx.moveTo(100, 150);
      ctx.arc(125, 125, 25, 0, Math.PI * 2, true);

      ctx.fill();

      let imageHttp = Platform.OS === 'web' ? new Image() : new GImage();
      imageHttp.onload = () => {
        ctx.drawImage(imageHttp, 70, 0, 112, 37);
      };

      imageHttp.src =
        'https://gw.alicdn.com/tfs/TB1KwRTlh6I8KJjy0FgXXXXzVXa-225-75.png';
    }}/>
  </>
}`
基本抄的示例，没啥特别的

**Comment by flyskywhy** [comment]
刚发布的 @flyskywhy/react-native-gcanvas@2.0.1 已解决该问题 😄

**Comment by WhyCloudy** [comment]
> 刚发布的 @flyskywhy/react-native-gcanvas@2.0.1 已解决该问题 😄

好的，我试下，多谢您啦
