### ISSUE TITLE
与上游版本字体大小不同的请教

### ISSUE THREAD

**Issue by WhyCloudy** [flyskywhy/react-native-gcanvas#14]
#13 
跟上个问题有关的呢
在您修改2.0.1版本之前，其实我一直都是使用的官方版本的GCanvas（也就是说，我**没有**在podfile里面加上README Getting Start中额外添加的那一行，而是yarn install后，直接pod install，自动安装了GCanvas的1.2.0版本）
在您推送了2.0.1后，我在Podfile中加入了引用行，再次pod install后GCanvas的版本降为1.1.1，数字0终于消失了

但是我发现两个不同版本的GCanvas，同样24px的字体，渲染出来的文字却是不一样大小的
1.2.0大一些，1.1.1显得十分小

想问下您是否了解这个情况嘞😬

**Comment by flyskywhy** [comment]
我查了一下 git 历史记录：

* 2019-12-31 官方发布了 ios 1.1.1
* 2020-07-06 官方在 master 分支中删除  weex bridge 和 react-native bridge ，且在 issue 中宣布不再支持 react-native
* 然后官方一直在 node_canvas 分支中对新增的 node 版本进行更新
* 2020-12-13 我解决了原先 reac-native bridge 的许多运行问题并开始发布新版 @flyskywhy/react-native-gcanvas
* 2021-02-23 官方不知出于什么想法在一个叫 merge_new_version 的分支中合并了 node_canvas 分支然后发布了 ios 1.2.0 ，而且该分支中其中也保留着并未删除过的但不知还能否运行的  react-native bridge 代码

官方的 1.2.0 相较于 1.1.1 的确修改了很多字体相关的代码，而且从代码来看， #13 的问题只出现于 ios debug 版而非 release 版，所以你可以在你的 Podfile 中手动选择官方的 1.2.0 或 1.1.1 版本，或是用我的 README 中的那一行自动选择我的 1.1.1 版本。

**Comment by WhyCloudy** [comment]
好的，真是麻烦您了，以后我再diff一下看下 为啥大小会变化吧，后续就直接使用您的1.1.1版本了
多谢啦

**Comment by flyskywhy** [comment]
如果你要用于产品化的话，请注意这个来自苹果的幺蛾子 #11

**Comment by WhyCloudy** [comment]
> 如果你要用于产品化的话，请注意这个来自苹果的幺蛾子 #11

好的👌，不过我只是做个自用的app，对ios环境也不是特别熟悉，只输出ios端……希望没啥太大影响

**Comment by flyskywhy** [comment]
@flyskywhy/react-native-gcanvas@3.0.0 解决了字体显得十分小的问题
