### ISSUE TITLE
App just doesn't open it 

### ISSUE THREAD

**Issue by LuisCarlos-Maia** [flyskywhy/react-native-gcanvas#16]
after following the instructions here i managed to build an app but now my app does not open i try to open it and nothing.

I wanted to be able to use the canvas to draw images and manipulate with the composition similar to the canvas html5 but it didn't work. could help me? the worst i have no error message or something the app just doesn't open it closes by itself

**Comment by flyskywhy** [comment]
Is your phone Android or iOS?

Can you give the `adb logcat` result?

Have you trid a whole new proj like `react-native init TestCanvasProj --version 0.63.2` and use the example in README.md?

**Comment by LuisCarlos-Maia** [comment]
I'm using emulator! And I didn't create it with react-native init
TestCanvasProj --version 0.63.2 .
I didn't know this possibility existed. I looked at the documentation and
didn't see, maybe try to create a new project with this command.
Thanks for answering.

Em ter., 8 de jun. de 2021 às 21:18, Li Zheng ***@***.***>
escreveu:

**Comment by flyskywhy** [comment]
Because most emulator is x86, and react-native-gcanvas only support arm, so you have to use a real phone.
