### ISSUE TITLE
Build fail on Android, deprecated Gradle features 

### ISSUE THREAD

**Issue by Ayomide57** [flyskywhy/react-native-gcanvas#19]
please kindly upgrade or if there is a way to fix this issue i would really appreciate it 

![Screenshot 2021-06-16 at 11 53 29](https://user-images.githubusercontent.com/39005838/122207003-8d3f8300-ce99-11eb-82be-20e1be9cba94.png)

**Comment by Ayomide57** [comment]
i have also tried to down grade it to, gradle-6.5 , still getting the same issue

**Comment by flyskywhy** [comment]
It's not about gradle, please post the log after `> Configure project :android:gcanvas_library` which describe the detail of `Task :android:gcanvas_library:mergeDebugNativeLibs FAILED`

**Comment by flyskywhy** [comment]
Can you try add below into you `/android/app/build.gradle` and tell me the compile result?

```
android {
...
    ndkVersion "22.1.7171670"
...
```

**Comment by flyskywhy** [comment]
What's your ndk version? Have you tried above `ndkVersion "22.1.7171670"`

**Comment by Ayomide57** [comment]
yes i have  tried it

**Comment by Ayomide57** [comment]
![Screenshot 2021-06-19 at 14 47 08](https://user-images.githubusercontent.com/39005838/122644471-40fc7900-d10d-11eb-9f49-f834ae420609.png)


android/build.gradle

**Comment by flyskywhy** [comment]
I mean, not in your `/android/build.gradle` ,but in your `/android/app/build.gradle`, and like below:
```
android {
...
    ndkVersion "22.1.7171670"
...
```

**Comment by Ayomide57** [comment]
Okay i will do that now

**Comment by Ayomide57** [comment]
same error message 

   > More than one file was found with OS independent path 'lib/armeabi-v7a/libfreetype.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

**Comment by flyskywhy** [comment]
I have not try built `.apk` on macOS, can you try build `.ipa` on macOS, or build `.apk` on Linux/Windows ?

**Comment by Ayomide57** [comment]
ninja: Entering directory `/Users/usersystemname/Documents/animateApp/node_modules/@flyskywhy/react-native-gcanvas/android/gcanvas_library/.cxx/cmake/debug/armeabi-v7a'

**Comment by Ayomide57** [comment]
ninja: no work to do.

**Comment by flyskywhy** [comment]
I reproduced the issue with `RN0.64.2` not with `RN0.63.2`, and now `@flyskywhy/react-native-gcanvas"@2.3.1` fix it 😋

**Comment by Ayomide57** [comment]
hello 
thank you so much for the fix but my application crash now anytime i tried to view the page.
Do you have any idea what might be the issue ?

**Comment by flyskywhy** [comment]
Please post some logcat and your canvas related source code. And in another issue.

**Comment by flyskywhy** [comment]
v6.0.13 support x86 (Android emulator) now
