### ISSUE TITLE
Execution failed for task ':android:gcanvas_library:mergeDebugNativeLibs'.

### ISSUE THREAD

**Issue by Ayomide57** [flyskywhy/react-native-gcanvas#20]
![Screenshot 2021-06-16 at 11 53 29](https://user-images.githubusercontent.com/39005838/122643958-8f5c4880-d10a-11eb-8c47-dd2fd764c3e4.png)
![Screenshot 2021-06-16 at 13 03 28](https://user-images.githubusercontent.com/39005838/122643964-93886600-d10a-11eb-8216-596ddc55b29f.png)
![Screenshot 2021-06-19 at 14 24 51](https://user-images.githubusercontent.com/39005838/122643966-94b99300-d10a-11eb-9d96-feeba20499ec.png)
![Screenshot 2021-06-19 at 14 25 01](https://user-images.githubusercontent.com/39005838/122643968-95522980-d10a-11eb-9274-7892508cd7e8.png)

RN version     "react-native": "0.64.2",
React version    "react": "17.0.1",

**Comment by flyskywhy** [comment]
duplicated with #19
