### ISSUE TITLE
Application Short Down unexpectedly when trying to view particles page on react native 

### ISSUE THREAD

**Issue by Ayomide57** [flyskywhy/react-native-gcanvas#21]
RN 64

adb logcat screen 

![Screenshot 2021-06-21 at 13 36 03](https://user-images.githubusercontent.com/39005838/122765525-7e414200-d298-11eb-941f-d22b88a3b978.png)

**Comment by flyskywhy** [comment]
Emulator not real phone? gcanvas not support x86, and most emulator is x86. Please use real phone.

**Comment by Ayomide57** [comment]
Oh okay thanks
