### ISSUE TITLE
Support for iOS project without cocoapods

### ISSUE THREAD

**Issue by Nesh108** [flyskywhy/react-native-gcanvas#22]
Hello,

I would like to use this canvas in my project but the iOS part doesn't use cocoapods, so I am unable to add the spec.
What can I do?

**Comment by flyskywhy** [comment]
As `pod install` described in READEM.md, so what do you mean of "doesn't use cocoapods"?

**Comment by AlbertoMeQ** [comment]
My project doesn't use cocoapods, it's a bit old.

**Comment by flyskywhy** [comment]
Please upgrade your project to > RN0.62 ,or fork this and edit by yourself
