### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RCTGCanvasView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Ayomide57** [flyskywhy/react-native-gcanvas#23]
![Screenshot 2021-06-22 at 02 23 05](https://user-images.githubusercontent.com/39005838/123335424-570a9f00-d53c-11eb-979f-730bb314412b.png)
![Screenshot 2021-06-24 at 22 33 32](https://user-images.githubusercontent.com/39005838/123335436-5a9e2600-d53c-11eb-843a-d6243ad5ceac.png)

**Comment by flyskywhy** [comment]
Do you follow the README.md as also described below?

Add below into `/ios/Podfile`
```
  pod "GCanvas", :path => "../node_modules/@flyskywhy/react-native-gcanvas/GCanvas.podspec"
```
    cd YOUR_PROJECT/ios
    pod install

**Comment by Ayomide57** [comment]
i have done this

**Comment by Ayomide57** [comment]
and it is the same on android, i am testing it on both android and ios

**Comment by flyskywhy** [comment]
I have fix it in https://github.com/flyskywhy/react-native-particles-bg/issues/2 with the related commit https://github.com/flyskywhy/react-native-particles-bg/commit/9eebd9100b1bccb0924a2dc420d4e262d6047588 said:

    npm install @flyskywhy/react-native-gcanvas

And follow [the steps to install @flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas#react-native)

**Comment by Ayomide57** [comment]
i have this in my package and i have done it 
i will do it again or can i share my package.js 
i am using expo 41, with "react-native": "~0.63.4"

**Comment by flyskywhy** [comment]
Bare react-native project can use this

    npx react-native config

If `@flyskywhy/react-native-gcanvas` exist in packge.json, then in the output, if you can see `@flyskywhy/react-native-gcanvas`, then `RCTGCanvasView` will be auto linked in react-native building.

I don't know if expo project can do this. And why yours is package.js not package.json?

**Comment by Ayomide57** [comment]
sorry that was a mistake, it is package.json

**Comment by Ayomide57** [comment]
thank you, it is working fine now
