### ISSUE TITLE
WebGL performance

### ISSUE THREAD

**Issue by implicit-invocation** [flyskywhy/react-native-gcanvas#26]
I set up a basic example using `react-native-gcanvas` with WebGL.  
Multiple instances of a texture are drawn on the canvas using a sprite batch (use `drawElements` on indexed vertices).  
The same setup, when running on safari, can spawn up to ~30000 instances on my iPhone X with stable 60fps.  
But the performance is very poor with this library. More than 100 instances can make the frame rate drop.  
Is that how it's supposed to be? Or am I missing anything?

**Comment by flyskywhy** [comment]
And the instances result on Android?

**Comment by flyskywhy** [comment]
v2.3.12 fixed it.
