### ISSUE TITLE
在react native 0.67.2中使用这个包，构建失败

### ISSUE THREAD

**Issue by weijintao92** [flyskywhy/react-native-gcanvas#37]
环境：    "@flyskywhy/react-native-gcanvas": "^2.3.18",
    "react": "17.0.2",
    "react-native": "0.67.2",
    
    
    错误：
![image](https://user-images.githubusercontent.com/47779463/156128437-762b5afd-07f3-46ef-a737-be2a256f239c.png)

**Comment by weijintao92** [comment]
感谢。我最开始的时候将这个配置写到babel.config.js里了。
![image](https://user-images.githubusercontent.com/47779463/156308700-c6f748f0-5c23-401b-936f-7cf56da3a553.png)

**Comment by weijintao92** [comment]
能不能给个纯粹的的 react native  列子啊

**Comment by flyskywhy** [comment]
这是一个纯粹的 react native 例子 https://github.com/flyskywhy/GCanvasRNExamples
