### ISSUE TITLE
can not fillText with thai font family

### ISSUE THREAD

**Issue by chukiatt** [flyskywhy/react-native-gcanvas#38]
Dear sir,

i cannot ctx.fillText('ภาษาไทย', 10, 10); with thai character font 

Please help me please..

**Comment by flyskywhy** [comment]
'ภาษาไทย' can be fillText on iOS, so it's just an Android issue.

The workaround can be `registerFont('/system/fonts/NotoSansThai-Regular.ttf');` since `@flyskywhy/react-native-gcanvas@5.1.7`.

The fix is WIP.

**Comment by flyskywhy** [comment]
`@flyskywhy/react-native-gcanvas@6.0.1` fixed this issue, no workaround of `registerFont` anymore.
