### ISSUE TITLE
Drawing svg

### ISSUE THREAD

**Issue by silverbuggy** [flyskywhy/react-native-gcanvas#40]
Does this library support drawing svg on the canvas?

**Comment by flyskywhy** [comment]
Can you try https://github.com/canvg/canvg or https://stackoverflow.com/questions/3768565/drawing-an-svg-file-on-a-html5-canvas or https://stackoverflow.com/questions/2907537/how-to-convert-svg-files-to-html5s-canvas
and tell me the result?

**Comment by gydroperit** [comment]
canvg is working

**Comment by flyskywhy** [comment]
Thanks @gydroperit
