### ISSUE TITLE
React 17 or 18 compatibility and support

### ISSUE THREAD

**Issue by kungfoolabs** [flyskywhy/react-native-gcanvas#43]
Just getting started with Gcanvas! Love the demos and performance.

However, getting started with a new project, I am seeing peer dependency clashes

> npm WARN ERESOLVE overriding peer dependency
> npm WARN While resolving: react-shallow-renderer@16.14.1
> npm WARN Found: react@18.0.0
> npm WARN node_modules/react
> npm WARN   peer react@"18.0.0" from react-native@0.69.1
> npm WARN   node_modules/react-native
> npm WARN     peer react-native@"*" from @react-native-community/cli@8.0.3
> npm WARN     node_modules/@react-native-community/cli
> npm WARN     2 more (the root project, @flyskywhy/react-native-browser-polyfill)
> npm WARN   4 more (react-test-renderer, react-shallow-renderer, ...)
> npm WARN 
> npm WARN Could not resolve dependency:
> npm WARN peer react@"^16.0.0 || ^17.0.0" from react-shallow-renderer@16.14.1
> npm WARN node_modules/react-shallow-renderer
> npm WARN   react-shallow-renderer@"16.14.1" from react-native@0.69.1
> npm WARN   node_modules/react-native
> npm WARN 
> npm WARN Conflicting peer dependency: react@17.0.2
> npm WARN node_modules/react
> npm WARN   peer react@"^16.0.0 || ^17.0.0" from react-shallow-renderer@16.14.1
> npm WARN   node_modules/react-shallow-renderer
> npm WARN     react-shallow-renderer@"16.14.1" from react-native@0.69.1
> npm WARN     node_modules/react-native
> npm WARN deprecated text-encoding@0.7.0: no longer maintained
> npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

I understand this is just a warning, but will there be continued support for later versions of react?

**Comment by flyskywhy** [comment]
So, looks like it's already support react 18? :stuck_out_tongue_closed_eyes: 

Maybe I should change `"react": "^16.8.6"` to `"react": "*"` in @flyskywhy/react-native-browser-polyfill just to suppress the warning?

You can create issue If you found bug, I will try to fix when I'm not too busy.

**Comment by kungfoolabs** [comment]
Haha. Thanks @flyskywhy! Got your demo SnakeRN working so will be starting there. 

Appreciate the continued support
