### ISSUE TITLE
ARC Semantic Issue (iOS)

### ISSUE THREAD

**Issue by Tebrynn** [flyskywhy/react-native-gcanvas#44]
`...../node_modules/@flyskywhy/react-native-gcanvas/ios/RCTGCanvasModule.m:81:25: No visible @interface for 'GCanvasModule' declares the selector 'disable:'`

I've got these 4 errors:
No visible @interface for 'GCanvasModule' declares the selector 'disable:'
No visible @interface for 'GCanvasModule' declares the selector 'setDevicePixelRatio:ratio:'
No visible @interface for 'GCanvasModule' declares the selector 'resetGlViewport:'
No visible @interface for 'GCanvasModule' declares the selector 'render:commands:type:'

I installed latest version (2.3.24)
Any idea?

**Comment by flyskywhy** [comment]
Do you (as README.md described)：

Add below into `/ios/Podfile`
```
  pod "GCanvas", :path => "../node_modules/@flyskywhy/react-native-gcanvas/GCanvas.podspec"
```
    cd YOUR_PROJECT/ios
    pod install

**Comment by Tebrynn** [comment]
ye i've done it tnx but now i see only a black screen. I logged canvas width and height and inside render method (proton part). Logs seems correct but nothing happens. I tried on both emulator and real device. No errors only a warning when i unmount component.
I tried a previous version 2.3.0 and it seems to work.
`    "react": "18.0.0",
    "react-native": "0.69.1",`

**Comment by flyskywhy** [comment]
Maybe react-native-gcanvas is not support react-native 0.69, please try lower version rn for test, and tell me the result, thanks.

**Comment by Tebrynn** [comment]
I think the problem is the listener. I made it work sometimes but i see a lot of memory leaks. It doesn't unmount when i unmount the parent component

**Comment by flyskywhy** [comment]
version 2.3.22 fix iOS memory leak, can you try it?

**Comment by flyskywhy** [comment]
version 2.3.26 fixed `EventEmitter.removeListener ... Method has been deprecated`
