### ISSUE TITLE
Zdog rendering in Gcanvas is different from the web

### ISSUE THREAD

**Issue by kungfoolabs** [flyskywhy/react-native-gcanvas#46]
Hi @flyskywhy ! Been doing more testing with the library and following the Zdog instructions will the polyfill. 

While the cake example works perfectly, when I copied the code for the below, the rendering was different:
https://codepen.io/desandro/pen/qxjmKM
https://codepen.io/desandro/pen/aqYXoa

The fidelity of the rendering in the Kirby is not nearly as high and you can see the lines. Not sure if this is because of the polyfill or because of Gcanvas.

For Mario, the eyes are partially rendered.

If I load the same codepen in a webview, it renders perfectly (as expected).

The reason why I am asking is because I prefer a native implementation through Gcanvas for performance reasons but don't want to hit rendering issues mid development. Any thoughts?!

Thanks in advance!

<img width="437" alt="Screenshot 2022-09-05 at 1 59 29 PM" src="https://user-images.githubusercontent.com/1711449/188371019-61d8382e-78a8-4273-a363-c4ccf716d74f.png">

<img width="437" alt="Screenshot 2022-09-05 at 1 59 29 PM" src="https://user-images.githubusercontent.com/1711449/188370998-012a2bd6-a317-4334-9ea1-8cd0ee8029f2.png">

**Comment by kungfoolabs** [comment]
@flyskywhy just checking to see if you might know why the distorations are happening?

**Comment by flyskywhy** [comment]
Ok, I'll try it in days.

**Comment by flyskywhy** [comment]
v2.3.25 fix the issue 😄

**Comment by kungfoolabs** [comment]
Wow! Awsome - thanks so much. I see, it looks like a scaling issue
