### ISSUE TITLE
How can I use Pixi

### ISSUE THREAD

**Issue by Timson020** [flyskywhy/react-native-gcanvas#47]
Can I Use gcanvas in release app ?

I recently used pixi

but I hava problem in pixi 6.5.2

**Comment by Timson020** [comment]
```
 TypeError: gl.getParameter is not a function. (In 'gl.getParameter(gl.MAX_VERTEX_ATTRIBS)', 'gl.getParameter' is undefined)

```
It is message use in expo-pixi

**Comment by flyskywhy** [comment]
My [https://github.com/flyskywhy/snakeRN](https://github.com/flyskywhy/snakeRN) game (can be comiled as release) used my [https://github.com/flyskywhy/react-native-pixi](https://github.com/flyskywhy/react-native-pixi) which combine pixi.js@4.7.0 and `@flyskywhy/react-native-gcanvas` :stuck_out_tongue_closed_eyes:

**Comment by Timson020** [comment]
I use 
```
function createText() {
	const skewStyle = new PIXI.TextStyle({
		fontFamily: 'Arial',
		dropShadow: true,
		dropShadowAlpha: 0.8,
		dropShadowAngle: 2.1,
		dropShadowBlur: 4,
		dropShadowColor: '0x111111',
		dropShadowDistance: 10,
		fill: ['#ffffff'],
		stroke: '#004620',
		fontSize: 60,
		fontWeight: 'lighter',
		lineJoin: 'round',
		strokeThickness: 12
	})
	const skewText = new PIXI.Text('Hello PixiJS', skewStyle)
	skewText.x = 10
	skewText.y = 100
	stage.addChild(skewText)
}
```

error msg 
```
context.scale is not a function
```

**Comment by flyskywhy** [comment]
Fixed in https://github.com/pixijs/pixijs/issues/5723#issuecomment-1411277994
