### ISSUE TITLE
绘制的线有明显的锯齿

### ISSUE THREAD

**Issue by hanhailong** [flyskywhy/react-native-gcanvas#48]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/4241807/192184733-36696100-2fca-4aee-bbde-22a10991ee27.png">

试了几个方案，都不起作用

**Comment by flyskywhy** [comment]
你试过在 <GCanvasView/> 中添加属性 devicePixelRatio={1} 吗？

**Comment by hanhailong** [comment]
> devicePixelRatio

试了，不好使，这个设置devicePixelRatio={1} 后绘制出来的图表变小了，但是还是有锯齿

Gcanvas底层绘制2D使用的OpenGL，感觉需要从OpenGL测入手， https://blog.csdn.net/u014248312/article/details/78027383   刚开始看这块，得研究研究 @flyskywhy

**Comment by flyskywhy** [comment]
`@flyskywhy/react-native-gcanvas@4.0.0` 在 Android 上解决了锯齿问题， iOS 欠奉

**Comment by flyskywhy** [comment]
`@flyskywhy/react-native-gcanvas@6.0.0` 默认关闭了抗锯齿，如果使用该版本并希望开启抗锯齿的，请多加个 prop :

    isEnableFboMsaa={true}
