### ISSUE TITLE
Invariant Violation: requireNativeComponent: "GCanvasView" was not found in the UIManager

### ISSUE THREAD

**Issue by muh-hamada** [flyskywhy/react-native-gcanvas#50]
Hi,

I'm trying to get my app working after adding `react-native-gcanvas` but I get this error all the time:

> Invariant Violation: requireNativeComponent: "GCanvasView" was not found in the UIManager

I am running on Android and I followed the instructions here https://github.com/flyskywhy/react-native-gcanvas#getting-started

FYI, I'm using expo and running the bare flow, these are the versions:
```
   "@flyskywhy/react-native-gcanvas": "^2.3.27",
    "abab": "^2.0.6",
    "expo": "~46.0.16",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.5",
    "react-native-web": "~0.18.7"
```

I don't know what did I miss. **I'd really appreciate your support here.**

**Comment by flyskywhy** [comment]
Seems you have done in 'react-native.config.js', right? Then could you firstly try `react-native@0.63.2` without expo (which I'm working on well)?

**Comment by muh-hamada** [comment]
> without expo (which I'm working on well) and tell me the result?

@flyskywhy do you mean creating a new react-native project without using expo? There is no way for it to work with expo?

**Comment by flyskywhy** [comment]
I'm not saying "no way for it to work with expo", I just want you have a test.

**Comment by muh-hamada** [comment]
I tried again with react-native and it worked.

**Comment by flyskywhy** [comment]
react-native@0.69.5 work?
expo not work?
