### ISSUE TITLE
Custom Font not working

### ISSUE THREAD

**Issue by themaxsmith** [flyskywhy/react-native-gcanvas#51]
Tried to use a custom font on iOS and it does not work.

I think the issue is due to openGL ES deprecation or supporting the library, it seems like even the new Apple system fonts do not work.

I would really like to see this library get Metal support

**Comment by flyskywhy** [comment]
For Metal support, maybe you can consider use [MetalANGLE](https://github.com/kakashidinho/metalangle) framework as #11 described, thanks :stuck_out_tongue_closed_eyes:

**Comment by flyskywhy** [comment]
I test custom font on iOS and it's OK (Android also OK), maybe you need follow the steps to install custom font as described in `README.md` since `@flyskywhy/react-native-gcanvas@5.1.7`.
