### ISSUE TITLE
Unable to compile iOS due to missing return value

### ISSUE THREAD

**Issue by toysonlocation** [flyskywhy/react-native-gcanvas#58]
I had to add line 122 `return nil` to setDevicePixelRatio to get it to compile. Please advise if there is some other problem.

![image](https://user-images.githubusercontent.com/39204807/219463227-3918bdc6-f4cf-4857-892c-44341cfe12dc.png)

**Comment by flyskywhy** [comment]
Thanks, and here comes v5.1.6 :stuck_out_tongue:
