### ISSUE TITLE
Cant build on react native 0.72.0

### ISSUE THREAD

**Issue by kocendavid** [flyskywhy/react-native-gcanvas#65]
Update of CompileSDK and targetSDK is needed to to build project on react native 0.72. Ideally version 31 since new play store releases should have at least this version.

**Comment by nahlebn1k** [comment]
Same issue, update lib please.
RN version 0.72.3

**Comment by flyskywhy** [comment]
@nahlebn1k , please test the commit https://github.com/flyskywhy/react-native-gcanvas/commit/3b5445dadf92c580c1f1d279bc21b29f4e0c6db8 on Linux and Windows, then tell me the result.

**Comment by nahlebn1k** [comment]
@flyskywhy not able to test on Linux now, but Windows seems to work fine. Thank you very much!

**Comment by flyskywhy** [comment]
@flyskywhy/react-native-gcanvas@6.0.11 fix it :smile:
