### ISSUE TITLE
<GCanvasView> component in <FlatList> doesn't render anything

### ISSUE THREAD

**Issue by nahlebn1k** [flyskywhy/react-native-gcanvas#71]
I'm trying to call GCanvasView component in FlatList but got nothing. On first screen my old svg renders that works fine and blank spaces that is GCanvasView calls.
![image](https://github.com/flyskywhy/react-native-gcanvas/assets/106028799/e6443b9a-bd1d-4bf3-8c8b-640213385c31)

But on main screen it works fine and renders canvas perfectly.
![image](https://github.com/flyskywhy/react-native-gcanvas/assets/106028799/f395c5b6-3b7d-42d4-80f9-e76cccb65540)

Here is my code
```
const onCanvasCreate = canvas => {
    console.log('redraw', width, height, name)
    const ctx = canvas.getContext('2d')
    ctx.clearRect(0, 0, canvas.width, canvas.height)
    ctx.translate(width/2 + 0.5, height/2 + 0.5)
    ctx.scale(scaleX, scaleY)
    //render function
    reticleSwitcher(ctx, name, themeStyles.theme, mradUp, mradRight, targetDistanceForCalc, targetType)
  }
  
 return (
    <GCanvasView
      onCanvasCreate={onCanvasCreate}
      style={{width: width, height: height}}
    />
  )
```

**Comment by flyskywhy** [comment]
It seems your <FlatList> is in a <Modal>, Please try `@flyskywhy/react-native-modal-animated` instead and tell me the result.

**Comment by nahlebn1k** [comment]
@flyskywhy Thank you now it works! But i found new issue with text.replace
![image](https://github.com/flyskywhy/react-native-gcanvas/assets/106028799/d8fefb72-48f9-4b2b-9941-2581e8a06db6)

**Comment by nahlebn1k** [comment]
Fixed it already, i was passing number value instead of string.

I have last question. How can i disable built in touch event in <GCanvasView> to make work <TouchableOppacity> of parent component?

**Comment by flyskywhy** [comment]
Use this props

    isGestureResponsible={false}

**Comment by nahlebn1k** [comment]
Thank you.
