### ISSUE TITLE
能不能不依赖于 react-native-browser-polyfill

### ISSUE THREAD

**Issue by kerm1it** [flyskywhy/react-native-gcanvas#73]
发现在 `GCanvasComponent` 文件中用到了 `react-native-browser-polyfill`，这就会导致全局环境被污染

有一些其他库是判断了当前环境是否是 dom 或者浏览器环境，polyfill 之后就会有误判，因为这样就是个伪浏览器环境，但是这个库是在 react-native 环境运行的，给了其他一些库例如 `echarts` 一些错误的信息，导致运行出错，例如根据 `typeof document !== undefined` 来判断是否支持 dom，polyfill 之后是支持的，一些库就调用 浏览器相关的 api，最后又发现没有，导致报错

**Comment by flyskywhy** [comment]
因为 canvas 原本是 Web 上的，因此很多第三方软件使用 canvas 时会使用 Web 的方式来调用 canvas ，比如 `document.createElement('canvas')` 这样的，为了方便移植那么多现成的 canvas 第三方软件，故此依赖了 `react-native-browser-polyfill` ，也因此不会取消这个依赖。

针对你的问题，比如 `echarts` ，实际上 `echarts` 也是一个使用到了 canvas 的第三方组件，所以解决的方法是请自行将其移植，并期待你将其发布为比如 `react-native-echarts-gcanvas` 之类的 :stuck_out_tongue_closed_eyes:

**Comment by kerm1it** [comment]
但是这个库本来就是运行在 react-native 环境的呀？在 react-native 环境里面，document 本身就是不存在的，不能为了兼容 web 环境的调用就把 react-native 的环境污染了吧？在 react-naive 环境里面，使用 document.createElement 这种方法才是错的吧？web 调用是不能放在 react-native 环境，正确的做法应该这些第三方组件为了兼容 react-native 环境，去做一些 web 环境的逻辑抽离？

而且你做 polyfill 本身并没有错，但是目前的做法是污染全局环境，导致其他库出现了问题，这样应该不是好的实践方式吧？

**Comment by kerm1it** [comment]
而且我们本地用 echarts 的时候，如果没有 gcanvas 这个库，是可以正常渲染出来的，它里面有环境判断，如果发现支持 dom，就会走浏览器环境，但是目前这个浏览器环境 polyfill 功能又不全，就导致运行出错了
