### ISSUE TITLE
Issue with async component render

### ISSUE THREAD

**Issue by nahlebn1k** [flyskywhy/react-native-gcanvas#74]
I have some async calculations in my app that implemented with 2 different UseEffect hooks. Here is simplified version, can't share full code but i think it will be enough for understanding. So the problem is that `<GCanvas>` component renders only after all useEffects ended their work. First video is default SVG render that works fine and second with `<GCanvas>` render. Is there any workaround about this issue? Thanks in advance!

https://github.com/flyskywhy/react-native-gcanvas/assets/106028799/36e84163-6fd1-4683-8404-4c6a2b4b71ce

https://github.com/flyskywhy/react-native-gcanvas/assets/106028799/e4fc31a5-c6e5-454e-99a1-30bd19e838cd
```
const onCanvasCreate = canvas => {
    const ctx = canvas.getContext('2d')
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.translate(width/2 + 0.5, height/2 + 0.5)
    ctx.scale(scaleX, scaleY)

    // func with canvas methods
    reticleSwitcher(ctx, name, themeStyles.theme, mradUp, mradRight, 100, targetType)
}

React.useEffect(() => {
   // some calculactions for first screen
   setIsFirstScreenCalculaed(true)
}, [dataForCalculations])

React.useEffect(() => {
   // some calculactions for second screen
   setIsSecondScreenCalculaed(true)
}, [isFirstScreenCalculaed])

return (
   <View>
      // some code...

      {
         isFirstScreenCalculated ? (
            isCanvasRender ? (
               // render with GCanvas (Second Video)
               <GCanvasView
                  onCanvasCreate={onCanvasCreate}
                  style={{width: width, height: height}}
                  isGestureResponsible={false}
               />
            ) : // ... default SVG render (First Video)
         ) : <Preloader/>
      }

      // some code...
   </View>
)
```

**Comment by flyskywhy** [comment]
There is a typo in your code:

    isFirstScreenCalculaed
    isFirstScreenCalculated

maybe it is the typo that cause your problem?

**Comment by nahlebn1k** [comment]
@flyskywhy nope that is my mistake for simplified version, sorry. Original code is clean.

**Comment by flyskywhy** [comment]
I still can not dig out the cause of this render different. Maybe you have to try some workaround in your code by yourself.
