### ISSUE TITLE
dependency for audio fft , g canvas for ios is not working properly the errors i listed in description

### ISSUE THREAD

**Issue by ahmedIcots** [flyskywhy/react-native-gcanvas#75]
F/Users/ventura/Desktop/reactNative/folder/passages/ios/Pods/GCanvas'
duplicate symbol '_HandleInputBuffer' in:
/Users/ventura/Library/Developer/Xcode/DerivedData/passages-fvlgnkgwuqzcpqdcjgewfvbpcvob/Build/Products/Debug-iphonesimulator/RNAudioPcmStream/libRNAudioPcmStream.a(RNLiveAudioStream.o)
2)warning: no rule to process file '/Users/ventura/Desktop/reactNative/folder/passages/node_modules/@flyskywhy/react-native-gcanvas/core/src/gcanvas/shaders/shadow.glsl' of type 'text' for architecture 'x86_64' (in target 'GCanvas' from project 'Pods')
warning: no rule to process file

/Users/ventura/Library/Developer/Xcode/DerivedData/passages-fvlgnkgwuqzcpqdcjgewfvbpcvob/Build/Products/Debug-iphonesimulator/RNAudioRecord/libRNAudioRecord.a(RNAudioRecord.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The following build commands failed:
Ld /Users/ventura/Library/Developer/Xcode/DerivedData/passages-fvlgnkgwuqzcpqdcjgewfvbpcvob/Build/Products/Debug-iphonesimulator/passages.app/passages normal (in target 'passages' from project 'passages')
(1 failure)
]

**Comment by flyskywhy** [comment]
Maybe you can try real iPhone but not simulator, because iPhone is arm not x86_64, and gcanvas is not support x86.

**Comment by ahmedIcots** [comment]
did you test it? on real ios device?

**Comment by ahmedIcots** [comment]
are you sure @flyskywhy ? it works in ios real device and error is generically due to the ios simulator? or there is any way we can run this in ios simulator instead?

**Comment by flyskywhy** [comment]
Today I test again  https://github.com/flyskywhy/GCanvasRNExamples which include https://github.com/flyskywhy/react-native-live-audio-fft on real iPhone7, and runs well.

https://github.com/flyskywhy/react-native-gcanvas/assets/1439846/7cd44887-6078-4dc1-a2a0-1cbe05388d48

I'm not interest in ios simulator, so I don't know wether it's OK.

**Comment by ahmedIcots** [comment]
right then. thanks for letting me know
