### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Loovery** [flyskywhy/react-native-gcanvas#76]
UnsatisfiedLinkError
No implementation found for void com.taobao.gcanvas.GCanvasJNI.setContextType(java.lang.String, int) (tried Java_com_taobao_gcanvas_GCanvasJNI_setContextType and Java_com_taobao_gcanvas_GCanvasJNI_setContextType__Ljava_lang_String_2I)

**Comment by flyskywhy** [comment]
duplicated with #28
