### ISSUE TITLE
Support for react native v76

### ISSUE THREAD

**Issue by kocendavid** [flyskywhy/react-native-gcanvas#84]
Hey could you verify everything is up to date with react native 76? Unable to build on latest configuration.
My current build fails on this:
https://paste.gd/m8Tff6Xo

build.gradle

> buildscript {
>     ext {
>         buildToolsVersion = "35.0.0"
>         minSdkVersion = 24
>         compileSdkVersion = 35
>         targetSdkVersion = 34
>         ndkVersion = "26.1.10909125"
>         kotlinVersion = "1.9.24"
>     }
>     repositories {
>         google()
>         mavenCentral()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle")
>         classpath("com.facebook.react:react-native-gradle-plugin")
>         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
>     }
> }

settings.gradle

> pluginManagement { includeBuild("../node_modules/@react-native/gradle-plugin") }
> plugins { id("com.facebook.react.settings") }
> extensions.configure(com.facebook.react.ReactSettingsExtension) { ex -> ex.autolinkLibrariesFromCommand() }
> rootProject.name = 'SentienConnect'
> include ':app'
> includeBuild('../node_modules/@react-native/gradle-plugin')
> 
> include ':android:gcanvas_library'
> project(':android:gcanvas_library').projectDir = new File(rootProject.projectDir, '../node_modules/@flyskywhy/react-native-gcanvas/android/gcanvas_library')
> include ':android:bridge_spec'
> project(':android:bridge_spec').projectDir = new File(rootProject.projectDir, '../node_modules/@flyskywhy/react-native-gcanvas/android/bridge_spec')
> include ':android:adapters:gcanvas_imageloader_fresco'
> project(':android:adapters:gcanvas_imageloader_fresco').projectDir = new File(rootProject.projectDir, '../node_modules/@flyskywhy/react-native-gcanvas/android/adapters/gcanvas_imageloader_fresco')
> include ':android:adapters:bridge_adapter'
> project(':android:adapters:bridge_adapter').projectDir = new File(rootProject.projectDir, '../node_modules/@flyskywhy/react-native-gcanvas/android/adapters/bridge_adapter')

gradle wrapper

> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
> networkTimeout=10000
> validateDistributionUrl=true
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists

Thanks

**Comment by flyskywhy** [comment]
`@flyskywhy/react-native-gcanvas@6.0.15` should fix it.
