### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by yacaeh** [flyskywhy/react-native-gcanvas#9]
Hi I'm trying to install your module but I got this error? Any idea how to fix this?

```
/@flyskywhy/react-native-gcanvas/components/GCanvasComponent.js 32:19
Module parse failed: Unexpected token (32:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
| 
>   static propTypes = {
|     // isOffscreen: PropTypes.bool,
|     ...View.propTypes,
```

Another Error

```
node_modules/@flyskywhy/react-native-gcanvas/packages/gcanvas/src/env/image.js 6:17
Module parse failed: Unexpected token (6:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class GImage {
>   static GBridge = null;
| 
|   constructor() {
console.<computed> @ index.js:1
error @ react-native-logs.fx.ts:34
overrideMethod @ react_devtools_backend.js:2430
handleErrors @ webpackHotDevClient.js:174
../../../react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
```

**Comment by flyskywhy** [comment]
You're building Web, Right?

If you use latest `react-native-web`, you should not get this `Unexpected token` error.

Anyway, you can avoid the error by this:
```
if (Platform.OS !== 'web') {
  var GCanvasView = require('@flyskywhy/react-native-gcanvas').GCanvasView;
  var GImage = require(@flyskywhy/react-native-gcanvas').GImage;
}
```

**Comment by flyskywhy** [comment]
And because "React Native supports the web from version 0.60 upwards" ref to https://medium.com/crowdbotics/the-state-of-react-native-for-web-in-2021-3cf9209c95 , maybe you need upgrade your rn to 0.60+

**Comment by yacaeh** [comment]
@flyskywhy Thank you for the reply, 
Yes I'm building with web, and upgraded `react-native-web` to latest 0.15.0 and still having the same issue... 
I'm already using RN 0.63+ with expo SDK 39

**Comment by flyskywhy** [comment]
When I use `react-native-web`, I also use `react-app-rewired` as described in my blog:

[Install react-native-web with react-app-rewired](https://github.com/flyskywhy/g/blob/839907e0e653e06eb4e08880f02d0c60ea40f2ed/i%E4%B8%BB%E8%A7%82%E7%9A%84%E4%BD%93%E9%AA%8C%E6%96%B9%E5%BC%8F/t%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BD%93%E9%AA%8C/%E7%94%B5%E4%BF%A1/Tool/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80/JavaScript/React%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3.md#rn--060-%E7%9A%84%E5%AE%89%E8%A3%85-react-native-web)

With `react-app-rewired`, my react-native-web@0.15.0 and RN 0.63+ `without` expo project works fine, you can try it.
